# Generated by Django 2.2.5 on 2019-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='descricao')),
                ('imagem', models.ImageField(upload_to='media/', verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='preco')),
            ],
        ),
    ]
