# Generated by Django 2.2.7 on 2019-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='etapa',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Etapa'),
        ),
    ]
