# Generated by Django 2.2.7 on 2019-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191030_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ncasa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
