# Generated by Django 2.2.7 on 2019-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191111_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cep',
            field=models.CharField(max_length=8, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(max_length=254, null=True, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ncasa',
            field=models.CharField(max_length=6, null=True, verbose_name='ncasa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(max_length=9, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=254, verbose_name='email'),
        ),
    ]
