# Generated by Django 2.2.7 on 2019-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191111_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cep',
            field=models.CharField(default=59190000, max_length=8, verbose_name='cep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default=59190000, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(default=0, max_length=254, verbose_name='endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(default=1, upload_to='media/', verbose_name='foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ncasa',
            field=models.CharField(default=' ', max_length=6, verbose_name='ncasa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(default=' ', max_length=9, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
